disabled_rules:
  - identifier_name
  - opening_brace
  - trailing_comma
  - function_parameter_count
  - closure_parameter_position
  - multiple_closures_with_trailing_closure

# Find all the available rules by running: `swiftlint rules`
opt_in_rules:
  - empty_count

# excluded files
excluded:
  - "*/MockData.swift"

# configurable rules can be customized from this configuration file

force_cast: error
force_try: error

line_length:
  warning: 200
  error: 300

type_body_length:
  warning: 1000
  error: 1400

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]

identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - req
    - key
    - app
    - App
    - url
    - URL
    - res
    - sql
    - env
    - telemetry_api_server_version

#reporter: "github-actions-logging" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"